language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install codecov

install:
  - pip install .

script:
  - pytest --cov-report term --cov=pybackup tests/

after_success:
  - codecov
